[build]
  command = "npm run build"   # Build the Vite project
  publish = "dist"            # Directory to deploy (Vite outputs to 'dist')

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200